### ISSUE TITLE
Cannot post Spark event if Decimal type is in request

### ISSUE THREAD

**Issue by julijak** [MarquezProject/marquez#1551]
Posting Spark lineage event failing with HTTP 500 error if Decimal type field is in input/output dataset.
API logs:
`Can't handle field of type DECIMAL(10,2)`
`Can't handle field of type DECIMAL(7,2)`
DB logs:
`org.postgresql.util.PSQLException: ERROR: null value in column "type" violates not-null constraint`

marquez version: 0.16.1

**Comment by OleksandrDvornik** [comment]
@julijak can you please try once again. We have fixed similar issue in [PR](https://github.com/MarquezProject/marquez/pull/1553)

**Comment by julijak** [comment]
@OleksandrDvornik I can't check it until `marquezproject/marquez` docker image is updated.

**Comment by OleksandrDvornik** [comment]
@julijak you can run `docker/up.sh --build` to have the latest version of api. It will [build](https://github.com/MarquezProject/marquez/blob/main/docker-compose.dev.yml#L4) docker image for you.

**Comment by julijak** [comment]
@OleksandrDvornik tested again with local build, but it still fails. Here's the api log:

``` 
org.postgresql.util.PSQLException: ERROR: null value in column "type" violates not-null constraint
marquez-api     | !   Detail: Failing row contains (b97b1abb-fce5-4d35-9abb-4f6953c4a303, null, 2021-08-02 12:51:20.936, 2021-08-02 12:51:20.936, 24f5500f-f552-40bb-a01d-5990e961e3c1, rate, null). [statement:"/* DatasetFieldDao.upsert */ INSERT INTO dataset_fields (uuid, type, created_at, updated_at, dataset_uuid, name, description) VALUES (:uuid, :type, :now, :now, :datasetUuid, :name, :description) ON CONFLICT(dataset_uuid, name, type) DO UPDATE SET updated_at = EXCLUDED.updated_at, description = EXCLUDED.description RETURNING *", arguments:{positional:{0:b97b1abb-fce5-4d35-9abb-4f6953c4a303,1:2021-08-02T12:51:20.936Z,2:rate,3:null,4:null,5:24f5500f-f552-40bb-a01d-5990e961e3c1}, named:{now:2021-08-02T12:51:20.936Z,name:rate,description:null,type:null,datasetUuid:24f5500f-f552-40bb-a01d-5990e961e3c1,uuid:b97b1abb-fce5-4d35-9abb-4f6953c4a303}, finder:[]}]
```
Here's the part of the request that I assume causes the error:

```
 {
   "inputs":[
      {
         "namespace":"file",
         "name":"...",
         "facets":{
            "schema":{
               "_producer":"https://github.com/MarquezProject/marquez/tree/0.16.1/integrations/spark",
               "_schemaURL":"https://github.com/OpenLineage/OpenLineage/blob/main/spec/OpenLineage.json#SchemaDatasetFacet",
               "fields":[
                  {
                     "name":"id",
                     "type":"long"
                  },
                  {
                     "name":"rate",
                     "type":"decimal(10,2)"
                  }
               ]
            },
            "dataSource":{
               "..."
            }
         }
      }
   ]
}
```

**Comment by OleksandrDvornik** [comment]
@julijak, thank you, I found a root cause of that. Issue is with code in marquez.db.OpenLineageDao#toFieldType. In DB we have not-null constraint on field "type". in above method if we can't recognize type, we set null instead of Unknown.

**Comment by OleksandrDvornik** [comment]
@julijak, can you please try with latest code? fix was merged.

**Comment by julijak** [comment]
@OleksandrDvornik now it's fine, thanks.
